//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\estev\Desktop\Proyecto de Construccion\SSJ.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class SSJLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, PARENTESIS_DERECHO=8, 
		PARENTESIS_IZQUIERDO=9, COMILLAS=10, LLAVE_IZ=11, LLAVE_DR=12, IGUAL=13, 
		OPERADOR_RELACIONAL=14, OPERADOR_ARITMETICO=15, NUMERO=16, STRING=17, 
		TEXTO=18, WS=19;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "PARENTESIS_DERECHO", 
		"PARENTESIS_IZQUIERDO", "COMILLAS", "LLAVE_IZ", "LLAVE_DR", "IGUAL", "OPERADOR_RELACIONAL", 
		"OPERADOR_ARITMETICO", "NUMERO", "STRING", "TEXTO", "WS"
	};


	public SSJLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SSJLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'show'", "'if'", "'for'", "';'", "'else'", "'int'", "'string'", 
		"')'", "'('", "'\"'", "'{'", "'}'", "'='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, "PARENTESIS_DERECHO", 
		"PARENTESIS_IZQUIERDO", "COMILLAS", "LLAVE_IZ", "LLAVE_DR", "IGUAL", "OPERADOR_RELACIONAL", 
		"OPERADOR_ARITMETICO", "NUMERO", "STRING", "TEXTO", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SSJ.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SSJLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x15', 'y', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', 
		'\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x5', '\xF', ']', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x6', '\x11', '\x62', '\n', '\x11', '\r', '\x11', '\xE', 
		'\x11', '\x63', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', 'h', '\n', 
		'\x12', '\f', '\x12', '\xE', '\x12', 'k', '\v', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', 'q', '\n', 
		'\x13', '\f', '\x13', '\xE', '\x13', 't', '\v', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x2', '\x2', '\x15', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', '\x3', '\x2', '\t', '\x4', '\x2', '>', 
		'>', '@', '@', '\x6', '\x2', '\'', '\'', ',', '-', '/', '/', '\x31', '\x31', 
		'\x3', '\x2', '\x32', ';', '\x3', '\x2', '$', '$', '\x5', '\x2', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\x5', '\x2', '\v', '\f', '\xF', '\xF', 
		'\"', '\"', '\x2', '\x7F', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', 
		'\x2', '\x2', '\x3', ')', '\x3', '\x2', '\x2', '\x2', '\x5', '.', '\x3', 
		'\x2', '\x2', '\x2', '\a', '\x31', '\x3', '\x2', '\x2', '\x2', '\t', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\v', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\r', '<', '\x3', '\x2', '\x2', '\x2', '\xF', '@', '\x3', '\x2', '\x2', 
		'\x2', '\x11', 'G', '\x3', '\x2', '\x2', '\x2', '\x13', 'I', '\x3', '\x2', 
		'\x2', '\x2', '\x15', 'K', '\x3', '\x2', '\x2', '\x2', '\x17', 'M', '\x3', 
		'\x2', '\x2', '\x2', '\x19', 'O', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'Q', '\x3', '\x2', '\x2', '\x2', '\x1D', '\\', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', '^', '\x3', '\x2', '\x2', '\x2', '!', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '#', '\x65', '\x3', '\x2', '\x2', '\x2', '%', 'n', '\x3', '\x2', 
		'\x2', '\x2', '\'', 'u', '\x3', '\x2', '\x2', '\x2', ')', '*', '\a', 'u', 
		'\x2', '\x2', '*', '+', '\a', 'j', '\x2', '\x2', '+', ',', '\a', 'q', 
		'\x2', '\x2', ',', '-', '\a', 'y', '\x2', '\x2', '-', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '.', '/', '\a', 'k', '\x2', '\x2', '/', '\x30', '\a', 'h', 
		'\x2', '\x2', '\x30', '\x6', '\x3', '\x2', '\x2', '\x2', '\x31', '\x32', 
		'\a', 'h', '\x2', '\x2', '\x32', '\x33', '\a', 'q', '\x2', '\x2', '\x33', 
		'\x34', '\a', 't', '\x2', '\x2', '\x34', '\b', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x36', '\a', '=', '\x2', '\x2', '\x36', '\n', '\x3', '\x2', '\x2', 
		'\x2', '\x37', '\x38', '\a', 'g', '\x2', '\x2', '\x38', '\x39', '\a', 
		'n', '\x2', '\x2', '\x39', ':', '\a', 'u', '\x2', '\x2', ':', ';', '\a', 
		'g', '\x2', '\x2', ';', '\f', '\x3', '\x2', '\x2', '\x2', '<', '=', '\a', 
		'k', '\x2', '\x2', '=', '>', '\a', 'p', '\x2', '\x2', '>', '?', '\a', 
		'v', '\x2', '\x2', '?', '\xE', '\x3', '\x2', '\x2', '\x2', '@', '\x41', 
		'\a', 'u', '\x2', '\x2', '\x41', '\x42', '\a', 'v', '\x2', '\x2', '\x42', 
		'\x43', '\a', 't', '\x2', '\x2', '\x43', '\x44', '\a', 'k', '\x2', '\x2', 
		'\x44', '\x45', '\a', 'p', '\x2', '\x2', '\x45', '\x46', '\a', 'i', '\x2', 
		'\x2', '\x46', '\x10', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\a', '+', 
		'\x2', '\x2', 'H', '\x12', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\a', 
		'*', '\x2', '\x2', 'J', '\x14', '\x3', '\x2', '\x2', '\x2', 'K', 'L', 
		'\a', '$', '\x2', '\x2', 'L', '\x16', '\x3', '\x2', '\x2', '\x2', 'M', 
		'N', '\a', '}', '\x2', '\x2', 'N', '\x18', '\x3', '\x2', '\x2', '\x2', 
		'O', 'P', '\a', '\x7F', '\x2', '\x2', 'P', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'R', '\a', '?', '\x2', '\x2', 'R', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\a', '?', '\x2', '\x2', 'T', ']', '\a', '?', '\x2', 
		'\x2', 'U', 'V', '\a', '#', '\x2', '\x2', 'V', ']', '\a', '?', '\x2', 
		'\x2', 'W', ']', '\t', '\x2', '\x2', '\x2', 'X', 'Y', '\a', '@', '\x2', 
		'\x2', 'Y', ']', '\a', '?', '\x2', '\x2', 'Z', '[', '\a', '>', '\x2', 
		'\x2', '[', ']', '\a', '?', '\x2', '\x2', '\\', 'S', '\x3', '\x2', '\x2', 
		'\x2', '\\', 'U', '\x3', '\x2', '\x2', '\x2', '\\', 'W', '\x3', '\x2', 
		'\x2', '\x2', '\\', 'X', '\x3', '\x2', '\x2', '\x2', '\\', 'Z', '\x3', 
		'\x2', '\x2', '\x2', ']', '\x1E', '\x3', '\x2', '\x2', '\x2', '^', '_', 
		'\t', '\x3', '\x2', '\x2', '_', ' ', '\x3', '\x2', '\x2', '\x2', '`', 
		'\x62', '\t', '\x4', '\x2', '\x2', '\x61', '`', '\x3', '\x2', '\x2', '\x2', 
		'\x62', '\x63', '\x3', '\x2', '\x2', '\x2', '\x63', '\x61', '\x3', '\x2', 
		'\x2', '\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', '\"', 
		'\x3', '\x2', '\x2', '\x2', '\x65', 'i', '\a', '$', '\x2', '\x2', '\x66', 
		'h', '\n', '\x5', '\x2', '\x2', 'g', '\x66', '\x3', '\x2', '\x2', '\x2', 
		'h', 'k', '\x3', '\x2', '\x2', '\x2', 'i', 'g', '\x3', '\x2', '\x2', '\x2', 
		'i', 'j', '\x3', '\x2', '\x2', '\x2', 'j', 'l', '\x3', '\x2', '\x2', '\x2', 
		'k', 'i', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '$', '\x2', '\x2', 
		'm', '$', '\x3', '\x2', '\x2', '\x2', 'n', 'r', '\t', '\x6', '\x2', '\x2', 
		'o', 'q', '\t', '\a', '\x2', '\x2', 'p', 'o', '\x3', '\x2', '\x2', '\x2', 
		'q', 't', '\x3', '\x2', '\x2', '\x2', 'r', 'p', '\x3', '\x2', '\x2', '\x2', 
		'r', 's', '\x3', '\x2', '\x2', '\x2', 's', '&', '\x3', '\x2', '\x2', '\x2', 
		't', 'r', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\t', '\b', '\x2', '\x2', 
		'v', 'w', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\b', '\x14', '\x2', '\x2', 
		'x', '(', '\x3', '\x2', '\x2', '\x2', '\a', '\x2', '\\', '\x63', 'i', 
		'r', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
